workflows:
  build_only:
    name: Build Android App Only
    max_build_duration: 60

    environment:
      vars:
        JAVA_VERSION: 17
        GRADLE_OPTS: "-Xmx2048m"

    scripts:
      - name: Build Android app
        script: |
          echo "🔹 بدء عملية البناء..."
          ./gradlew clean assembleDebug --console=plain

    artifacts:
      - app/build/outputs/**/*.apk
