workflows:
  build_and_send_errors:
    name: Build & Send Errors
    max_build_duration: 60

    environment:
      vars:
        TELEGRAM_BOT_TOKEN:
          value: $TELEGRAM_BOT_TOKEN
          is_secret: true
        TELEGRAM_CHAT_ID:
          value: $TELEGRAM_CHAT_ID
          is_secret: true

    scripts:
      - name: Build Android app
        script: |
          echo "🔹 بدء بناء التطبيق..."
          ./gradlew assembleDebug --console=plain | tee "$CM_BUILD_DIR/build_full_log.txt"

      - name: Send build errors to Telegram
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          LOG_FILE="$CM_BUILD_DIR/build_full_log.txt"
          BOT_TOKEN="$TELEGRAM_BOT_TOKEN"
          CHAT_ID="$TELEGRAM_CHAT_ID"

          ERRORS=$(grep -iE "FAILURE|FATAL|Exception|error" "$LOG_FILE" || echo "(لا توجد أخطاء)")

          MAX_LEN=3800
          if [ ${#ERRORS} -gt $MAX_LEN ]; then
            ERRORS="... (تم اقتطاع الأجزاء السابقة) ...\n${ERRORS: -$MAX_LEN}"
          fi

          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="⚠️ Codemagic Build Errors:\n\n$ERRORS" \
            -d parse_mode="Markdown"

    artifacts:
      - $CM_BUILD_DIR/build_full_log.txt
