workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    scripts:
      - name: Build Debug APK
        script: |
          echo "Building Debug APK..."
          ./gradlew clean assembleDebug
      - name: Build Release APK
        script: |
          echo "Building Release APK..."
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
