name: Android CI Build with Telegram Notifications

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK and capture logs
        run: |
          set -o pipefail
          # توليد build_full.log حتى لو فشل البناء
          ./gradlew assembleDebug > build_full.log 2>&1 || true

      - name: Check APK exists
        run: |
          APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
          if [ ! -f "$APK_PATH" ]; then
            echo "APK not found, marking build as failed!"
            exit 1
          fi

      - name: Upload full build log as artifact
        if: failure() || success()
        uses: actions/upload-artifact@v4
        with:
          name: full-build-log
          path: build_full.log

      - name: Notify Telegram on Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: build_full.log
          message: |
            ❌ *Build Failed!*
            Repository: `${{ github.repository }}`
            Commit: `${{ github.sha }}`
            Branch: `${{ github.ref_name }}`
            
            Full build log is attached as TXT.

      - name: Notify Telegram on Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
          message: |
            ✅ *Build Successful!*
            Repository: `${{ github.repository }}`
            Commit: `${{ github.sha }}`
            Branch: `${{ github.ref_name }}`
            APK is ready for download.
          format: markdown
